name: CI-auth

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  test:
    name: Run lint and unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint --prefix frontend
  



